services:
  examples:
    image: ne2harbor.ne.ch/sgrf/sitn-examples
    pull_policy: always
    build:
      context: examples
    restart: unless-stopped
    ports:
      - "5022:80"

  docusaurus:
    image: ne2harbor.ne.ch/sgrf/sitn-docs
    pull_policy: always
    build:
      context: docusaurus
    restart: unless-stopped
    ports:
      - "5023:80"